// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdjfhufubrngkilgzecw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkamZodWZ1YnJuZ2tpbGd6ZWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDI5MjAsImV4cCI6MjA2NzIxODkyMH0.FTBqAnhRx5rJbhJPcpWf8CZ1gb-1Xhi77Nz_Cka4w1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});