// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhkufibfwskdpzdjwirr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oa3VmaWJmd3NrZHB6ZGp3aXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzcwNDcsImV4cCI6MjA2NzMxMzA0N30.ocKAuYTWxj4DUQGdFkRP4rcVy02nBqRqGjT2VopSsXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if we're in a browser environment
const isBrowser = typeof window !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: true,
  }
});