name: DB Drift Check
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install Supabase CLI
        run: npm i -g supabase@latest

      - name: Link to project (safe: no writes)
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF"

      - name: Run drift check
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_CI: "1"
        run: bash scripts/check_drift.sh